# Generated by Django 5.0.1 on 2024-01-23 08:07

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='foldername',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='folderuser',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Formål',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Sendt_til_DLA',
        ),
        migrations.AddField(
            model_name='file',
            name='files',
            field=models.FileField(default=1, upload_to=website.models.get_file_location),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='website.record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='Formaal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Negotiation', 'NEGOTIATION'), ('Lead', 'LEAD'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lost', 'LOST'), ('Vælg', 'Vælg'), ('Lukket aftale', 'LUKKET AFTALE')], default='Vælg', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allfiles', to='website.folder'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Stefan', 'Stefan'), ('Benjamin', 'BENJAMIN'), ('Jakob', 'JAKOB'), ('Magnus', 'MAGNUS'), ('Thomas', 'THOMAS'), ('Vælg', 'Vælg')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
