# Generated by Django 5.0.1 on 2024-01-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_record_postnummer_alter_record_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Benjamin', 'BENJAMIN'), ('Stefan', 'Stefan'), ('Magnus', 'MAGNUS'), ('Thomas', 'THOMAS'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Negotiation', 'NEGOTIATION'), ('Lost', 'LOST'), ('Vælg', 'Vælg'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lead', 'LEAD')], default='Vælg', max_length=20),
        ),
    ]
