# Generated by Django 5.0.1 on 2024-01-24 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_record_lead_alter_record_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Jakob', 'JAKOB'), ('Thomas', 'THOMAS'), ('Benjamin', 'BENJAMIN'), ('Magnus', 'MAGNUS'), ('Stefan', 'Stefan')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Sendt til DLA', 'SENDT TIL DLA'), ('Lead', 'LEAD'), ('Vælg', 'Vælg'), ('Negotiation', 'NEGOTIATION'), ('Lost', 'LOST'), ('Lukket aftale', 'LUKKET AFTALE')], default='Vælg', max_length=20),
        ),
    ]
