# Generated by Django 5.0.1 on 2024-01-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_comment_name_comment_user_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Thomas', 'THOMAS'), ('Stefan', 'Stefan'), ('Jakob', 'JAKOB'), ('Benjamin', 'BENJAMIN'), ('Magnus', 'MAGNUS'), ('Vælg', 'Vælg')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Negotiation', 'NEGOTIATION'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lost', 'LOST'), ('Lead', 'LEAD'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
