# Generated by Django 5.0.1 on 2024-01-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Benjamin', 'BENJAMIN'), ('Thomas', 'THOMAS'), ('Magnus', 'MAGNUS'), ('Vælg', 'Vælg'), ('Jakob', 'JAKOB'), ('Stefan', 'Stefan')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lost', 'LOST'), ('Negotiation', 'NEGOTIATION'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
