# Generated by Django 5.0.1 on 2024-01-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Stefan', 'Stefan'), ('Jakob', 'JAKOB'), ('Vælg', 'Vælg'), ('Magnus', 'MAGNUS'), ('Thomas', 'THOMAS'), ('Benjamin', 'BENJAMIN')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Sendt til DLA', 'SENDT TIL DLA'), ('Negotiation', 'NEGOTIATION'), ('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lost', 'LOST'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
