# Generated by Django 5.0.1 on 2024-02-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_record_forfaldsdato_alter_comment_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Magnus', 'MAGNUS'), ('Benjamin', 'BENJAMIN'), ('Stefan', 'Stefan'), ('Vælg', 'Vælg'), ('Thomas', 'THOMAS'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Sendt til DLA', 'SENDT TIL DLA'), ('Lukket aftale', 'LUKKET AFTALE'), ('Negotiation', 'NEGOTIATION'), ('Lead', 'LEAD'), ('Lost', 'LOST'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
