# Generated by Django 5.0.1 on 2024-02-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_comment_created_on_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Magnus', 'MAGNUS'), ('Thomas', 'THOMAS'), ('Stefan', 'Stefan'), ('Benjamin', 'BENJAMIN'), ('Vælg', 'Vælg'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lost', 'LOST'), ('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE'), ('Negotiation', 'NEGOTIATION'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
