# Generated by Django 5.0.1 on 2024-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Stefan', 'Stefan'), ('Magnus', 'MAGNUS'), ('Jakob', 'JAKOB'), ('Thomas', 'THOMAS'), ('Vælg', 'Vælg'), ('Benjamin', 'BENJAMIN')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Negotiation', 'NEGOTIATION'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lost', 'LOST'), ('Lead', 'LEAD'), ('Vælg', 'Vælg'), ('Sendt til DLA', 'SENDT TIL DLA')], default='Vælg', max_length=20),
        ),
    ]
