# Generated by Django 5.0.1 on 2024-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Jakob', 'JAKOB'), ('Vælg', 'Vælg'), ('Thomas', 'THOMAS'), ('Benjamin', 'BENJAMIN'), ('Magnus', 'MAGNUS'), ('Stefan', 'Stefan')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Sendt til DLA', 'SENDT TIL DLA'), ('Vælg', 'Vælg'), ('Negotiation', 'NEGOTIATION'), ('Lost', 'LOST'), ('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE')], default='Vælg', max_length=20),
        ),
    ]
