# Generated by Django 5.0.1 on 2024-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Postnummer',
        ),
        migrations.AddField(
            model_name='record',
            name='Postnummer1',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Thomas', 'THOMAS'), ('Benjamin', 'BENJAMIN'), ('Jakob', 'JAKOB'), ('Stefan', 'Stefan'), ('Magnus', 'MAGNUS')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lost', 'LOST'), ('Lead', 'LEAD'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Negotiation', 'NEGOTIATION')], default='Vælg', max_length=20),
        ),
    ]
