# Generated by Django 5.0.1 on 2024-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_record_postnummer_record_postnummer1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Postnummer1',
            new_name='Postnummer',
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Magnus', 'MAGNUS'), ('Vælg', 'Vælg'), ('Jakob', 'JAKOB'), ('Stefan', 'Stefan'), ('Thomas', 'THOMAS'), ('Benjamin', 'BENJAMIN')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lead', 'LEAD'), ('Negotiation', 'NEGOTIATION'), ('Vælg', 'Vælg'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lost', 'LOST'), ('Lukket aftale', 'LUKKET AFTALE')], default='Vælg', max_length=20),
        ),
    ]
