# Generated by Django 5.0.1 on 2024-02-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_postnummer1_record_postnummer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='By',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Thomas', 'THOMAS'), ('Stefan', 'Stefan'), ('Jakob', 'JAKOB'), ('Vælg', 'Vælg'), ('Magnus', 'MAGNUS'), ('Benjamin', 'BENJAMIN')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Lead', 'LEAD'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Vælg', 'Vælg'), ('Negotiation', 'NEGOTIATION'), ('Lost', 'LOST')], default='Vælg', max_length=20),
        ),
    ]
