# Generated by Django 5.0.1 on 2024-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_record_by_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='By',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Benjamin', 'BENJAMIN'), ('Stefan', 'Stefan'), ('Magnus', 'MAGNUS'), ('Thomas', 'THOMAS'), ('Vælg', 'Vælg'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Lead', 'LEAD'), ('Negotiation', 'NEGOTIATION'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lost', 'LOST'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
