# Generated by Django 5.0.1 on 2024-02-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_record_pris_hektar_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Jakob', 'JAKOB'), ('Vælg', 'Vælg'), ('Stefan', 'Stefan'), ('Magnus', 'MAGNUS'), ('Benjamin', 'BENJAMIN'), ('Thomas', 'THOMAS')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Afventer underskrift', 'AFVENTER UNDERSKRIFT'), ('Vælg', 'Vælg'), ('Møde booket', 'MØDE BOOKET'), ('Lead', 'LEAD'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Negotiation', 'NEGOTIATION'), ('Lukket aftale', 'LUKKET AFTALE'), ('Bud og option udarbejdes', 'BUD OG OPTION UDAREJDES'), ('Lost', 'LOST')], default='Vælg', max_length=25),
        ),
    ]
