# Generated by Django 5.0.1 on 2024-02-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Pris_Hektar',
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Benjamin', 'BENJAMIN'), ('Jakob', 'JAKOB'), ('Stefan', 'Stefan'), ('Magnus', 'MAGNUS'), ('Thomas', 'THOMAS')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Lukket aftale', 'LUKKET AFTALE'), ('Møde booket', 'MØDE BOOKET'), ('Negotiation', 'NEGOTIATION'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Afventer underskrift', 'AFVENTER UNDERSKRIFT'), ('Bud og option udarbejdes', 'BUD OG OPTION UDAREJDES'), ('Lead', 'LEAD'), ('Lost', 'LOST')], default='Vælg', max_length=25),
        ),
    ]
