# Generated by Django 5.0.1 on 2024-02-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_record_pris_hektar_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Stefan', 'Stefan'), ('Jakob', 'JAKOB'), ('Benjamin', 'BENJAMIN'), ('Vælg', 'Vælg'), ('Magnus', 'MAGNUS'), ('Thomas', 'THOMAS')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Afventer underskrift', 'AFVENTER UNDERSKRIFT'), ('Negotiation', 'NEGOTIATION'), ('Møde booket', 'MØDE BOOKET'), ('Lead', 'LEAD'), ('Vælg', 'Vælg'), ('Lost', 'LOST'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Bud og option udarbejdes', 'BUD OG OPTION UDAREJDES')], default='Vælg', max_length=25),
        ),
    ]
