# Generated by Django 5.0.1 on 2024-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Jakob', 'JAKOB'), ('Stefan', 'Stefan'), ('Thomas', 'THOMAS'), ('Vælg', 'Vælg'), ('Benjamin', 'BENJAMIN'), ('Magnus', 'MAGNUS')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lead', 'LEAD'), ('Option udarbejdes', 'OPTION UDAREJDES'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Møde booket', 'MØDE BOOKET'), ('Negotiation', 'NEGOTIATION'), ('Vælg', 'Vælg'), ('Lost', 'LOST'), ('Lukket aftale', 'LUKKET AFTALE'), ('Afventer underskrift', 'AFVENTER UNDERSKRIFT'), ('Bud udarbejdes', 'BUD UDAREJDES')], default='Vælg', max_length=25),
        ),
    ]
