# Generated by Django 5.0.1 on 2024-02-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Lukket_aftale_Status',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Forhandlinger HoT', 'FORHANDLINGER HoT'), ('Forhandlinger SPA', 'FORHANDLINGER SPA'), ('Underskrevet HoT', 'UNDERSKREVET HoT'), ('Underskrevet SPA', 'UNDERSKREVET SPA'), ('Lukket sag', 'LUKKET SAG')], default='Vælg', max_length=30),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Benjamin', 'BENJAMIN'), ('Jacob', 'JACOB'), ('Magnus', 'MAGNUS'), ('Martine', 'MARTINE'), ('Stefan', 'Stefan'), ('Thomas', 'THOMAS')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Lead', 'LEAD'), ('Møde booket', 'MØDE BOOKET'), ('Møde afholdt', 'MØDE AFHOLDT'), ('Bud sendt', 'BUD SENDT'), ('Forhandling bud', 'FORHANDLING BUD'), ('Afventer DLA', 'AFVENTER DLA'), ('Forhandling option', 'FORHANDLING OPTION'), ('Afventer underskrift', 'AFVENTER UNDERSKRIFT'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lost', 'LOST')], default='Vælg', max_length=25),
        ),
    ]
