# Generated by Django 5.0.1 on 2024-02-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_record_lukket_aftale_status_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Moedestatus',
            field=models.CharField(choices=[('Møde booket', 'Møde booket'), ('Ombook', 'Ombook'), ('Møde aflyst', 'Møde aflyst'), ('Ikke relevant', 'Ikke relevant')], default='Møde booket', max_length=30),
        ),
    ]
