# Generated by Django 5.0.1 on 2024-02-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_record_moedestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Moedestatus',
        ),
    ]
