# Generated by Django 5.0.1 on 2024-02-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_record_moedestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Moedestatus',
            field=models.CharField(choices=[('Ikke relevant', 'Ikke relevant'), ('Møde booket', 'Møde booket'), ('Ombook', 'Ombook'), ('Møde aflyst', 'Møde aflyst')], default='Ikke relevant', max_length=30),
        ),
    ]
