# Generated by Django 5.0.1 on 2024-02-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_record_moedestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Moedestatus',
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Benjamin', 'BENJAMIN'), ('Jacob', 'JACOB'), ('Magnus', 'MAGNUS'), ('Martine', 'MARTINE'), ('Stefan', 'STEFAN'), ('Thomas', 'THOMAS')], default='Vælg', max_length=10),
        ),
    ]
