# Generated by Django 5.0.1 on 2024-02-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_remove_record_moedestatus_alter_record_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Moedestatus',
            field=models.CharField(blank=True, choices=[('Møde booket', 'Møde booket'), ('Ombook', 'Ombook'), ('Møde aflyst', 'Møde aflyst')], max_length=30),
        ),
    ]
