# Generated by Django 5.0.1 on 2024-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_record_opfølgningsdato'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Resights',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lukket_aftale_Status',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Option forlænges', 'OPTION FORLÆNGES'), ('Forhandlinger HoT', 'FORHANDLINGER HoT'), ('Forhandlinger SPA', 'FORHANDLINGER SPA'), ('Underskrevet HoT', 'UNDERSKREVET HoT'), ('Underskrevet SPA', 'UNDERSKREVET SPA'), ('Lukket sag', 'LUKKET SAG')], default='Vælg', max_length=30),
        ),
    ]
