# Generated by Django 4.2.7 on 2025-03-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_file_file_url_file_uploaded_on_file_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=False, auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True),
        ),

]